FROM cadic/pyspark-notebook

ARG NB_USER 1000
ARG NB_UID 100

LABEL maintainer="CADIC Jean Maximilien <maintainer@cadic.jp>"
ENV TAG="cadic_pyspark_notebook"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

