name: PySpark Docker Image

on:
  push:
    branches: ["dev", "master"]

  pull_request:
    branches: ["dev", "master"]

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make build_docker